version: '3.9'

services:
  backend:
    container_name: ${BACKEND_HOSTNAME:-backend}
    hostname: ${BACKEND_HOSTNAME:-backend}
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${BACKEND_INNER_PORT:-8000}"
    ports:
      - ${BACKEND_OUTER_PORT:-8000}:${BACKEND_INNER_PORT:-8000}
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    env_file:
      - .env
    ports:
      - ${REDIS_OUTER_PORT:-6379}:${REDIS_INNER_PORT:-6379}
