# Generated by Django 5.1.3 on 2024-11-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_channel_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
